### ISSUE TITLE
Support for naked variable references

### ISSUE THREAD

**Issue by kalifg** [ChessCom/alice#2]
You can't do this:

``` yaml
 forumTopic7:
        postCount: 100
        newCommentCount: $postCount
```

You have to do this:

``` yaml
 forumTopic7:
        postCount: 100
        newCommentCount: <numerify($postCount)>
```

or this:

``` yaml
 forumTopic7:
        postCount: 100
        newCommentCount: <stringify($postCount)>
```

And that won't work if the value you are referencing is not a number or string.  I don't see why the first example can't be supported, but right now the parser doesn't recognizing it as containing a variable because it's not between `<(` and `)>`.  Worse, it gets silently interpolating into a PHP variable (which likely becomes `0`) further down the line.

If we don't want to step on the ability to embed PHP perhaps we can just support something like `<($var)>`, a built-in identity operator?
